
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize dotfiles and alias
    command: . $GITPOD_REPO_ROOT/install.sh
ports:
  - port: 19000
    onOpen: ignore
    visibility: public
  - port: 19001
    onOpen: ignore
    visibility: public
  - port: 19002
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore  
  - port: 4040
    onOpen: ignore
    visibility: public
  - port: 5037
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - humao.rest-client