
image:
  file: .gitpod.Dockerfile

tasks:
  - command: source $GITPOD_REPO_ROOT/install.sh
ports:
  - port: 19000
    onOpen: ignore
    visibility: public
  - port: 19001
    onOpen: ignore
    visibility: public
  - port: 19002
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore

vscode:
  extensions:
    - humao.rest-client