
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize dotfiles and alias
    command: . $GITPOD_REPO_ROOT/install.sh
ports:
  - port: 19000-19002
    onOpen: ignore

vscode:
  extensions:
    - humao.rest-client